# Generated by Django 4.1.6 on 2023-02-08 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="admin",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
