# Generated by Django 4.1.6 on 2023-02-10 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory_app", "0003_productcategorie_image"),
    ]

    operations = [
        migrations.DeleteModel(
            name="orderHistory",
        ),
        migrations.DeleteModel(
            name="User",
        ),
    ]
