# Generated by Django 4.1.6 on 2023-02-11 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory_app", "0009_delete_admin"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="bu_code",
            field=models.CharField(max_length=30, null=True),
        ),
    ]
