# Generated by Django 4.1.6 on 2023-02-11 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory_app", "0013_alter_order_bucode"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="disabled",
            field=models.BooleanField(default=False),
        ),
    ]
