# Generated by Django 4.1.6 on 2023-02-12 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory_app", "0014_product_disabled"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Cart",
        ),
    ]
